# Generated by Django 2.2.24 on 2021-06-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_dashboard', '0002_bloodsample_chronusanalysis_cmpchronusanalysis_cmpcommercialanalysis_commercialanalysis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChronusAnalysis',
            new_name='ChronusCBC',
        ),
        migrations.RenameModel(
            old_name='CMPChronusAnalysis',
            new_name='ChronusCMP',
        ),
        migrations.RenameModel(
            old_name='CommercialAnalysis',
            new_name='CommercialCBC',
        ),
        migrations.RenameModel(
            old_name='CMPCommercialAnalysis',
            new_name='CommercialCMP',
        ),
    ]
